# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Package

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run build:chromium
    #- name: Package the extension
    #  uses: montudor/action-zip@v1
    #  with:
    #    args: zip -r extension.zip manifest.json assets lib options pages
        # args: zip -qq -r dir.zip dir
    - name: Package & upload extension (Chromium)
      uses: actions/upload-artifact@v4
      with:
        name: extension.chromium
        # path: extension.zip
        path: |
          manifest.json
          assets/*
          lib/*
          options/*
          pages/*
        compression-level: 6 # default compression (range: none 0...9 high)
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        # retention-days: 90

    - run: rm -f manifest.json

    - run: npm run build:gecko
    - name: Package & upload extension (Gecko)
      uses: actions/upload-artifact@v4
      with:
        name: extension.gecko
        path: |
          manifest.json
          assets/*
          lib/*
          options/*
          pages/*
        compression-level: 6
        if-no-files-found: error

# End.
